version: "3.9"  # optional since v1.27.0
services:
  balancer:
    image: nginx:latest
    container_name: balancer
    ports:
      - "80:80"
    networks:
      - bridge
    depends_on:
      - back
      - ui
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf

  database:
    image: postgres:12.6-alpine
    container_name: database
    restart: unless-stopped
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '15432:5432'
    networks:
      - bridge
    depends_on:
      - cache

  cache:
    image: redis:latest
    command: --port 6380
    expose:
      - 6380
    ports:
      - "6380:6379"
    networks:
      - bridge

  redis-pipe:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - bridge
    depends_on:
      - database

  data-generator:
    build: ./data-generator
    container_name: data-generator
    networks:
      - bridge
    depends_on:
      - bus

  bus:
    image: rabbitmq:3-management-alpine
    container_name: bus
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - bridge

  data-register:
    build: ./data-register
    container_name: data-register
    networks:
      - bridge
    depends_on:
      - data-generator
      - bus
      - redis-pipe
      - cache
      - database

  back:
    build: ./back-web-app
    container_name: back
    ports:
      - "9000:9000"
    networks:
      - bridge
    depends_on:
      - redis-pipe
      - cache
      - database

  ui:
    build: ./front-web-app
    container_name: ui
    ports:
      - "8080:8080"
    networks:
      - bridge

networks:
  bridge:
    driver: bridge